buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
    }
}

apply plugin: 'net.minecraftforge.gradle'

def rootProperties = new Properties()
new File(project.projectDir, '../../gradle.properties').withInputStream { rootProperties.load(it) }
def modVersion = rootProperties.mod_version
version = modVersion
group = 'haaa.picturebridge'
archivesBaseName = 'picturebridge-forge-1.12.2'
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'
    runs {
        client { workingDirectory project.file('run') }
    }
}

sourceSets.main.java.srcDir '../forge-common/src/main/java'

dependencies {
    minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2860'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('mcmod.info') {
        expand version: project.version, mcversion: '1.12.2'
    }
}

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
