package haaa.picturebridge.forge;

import haaa.picturebridge.forge.common.DecodedImage;
import haaa.picturebridge.forge.common.ImageLoadException;
import haaa.picturebridge.forge.common.RemoteImageLoader;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.GuiButton;
import net.minecraft.client.gui.GuiScreen;
import net.minecraft.client.resources.I18n;
import org.lwjgl.input.Keyboard;
import org.lwjgl.input.Mouse;
import org.lwjgl.opengl.GL11;

import java.io.IOException;
import java.net.URI;
import java.util.concurrent.CompletionException;
import java.util.concurrent.ExecutionException;

final class ImageViewerScreen extends GuiScreen {
    private final GuiScreen parent;private final URI uri;private AnimatedForgeTexture texture;private String error="";private int generation;private boolean started,dragging;private int lastX,lastY;private double zoom=1,panX,panY;private long copied,lastClick;
    ImageViewerScreen(GuiScreen parent,URI uri){this.parent=parent;this.uri=uri;}
    @Override public void initGui(){buttonList.clear();int w=Math.max(60,Math.min(96,(width-32)/3)),x=(width-w*3-10)/2,y=Math.max(0,height-27);buttonList.add(new GuiButton(0,x,y,w,20,tr("picturebridge.button.back")));buttonList.add(new GuiButton(1,x+w+5,y,w,20,tr("picturebridge.button.reload")));buttonList.add(new GuiButton(2,x+(w+5)*2,y,w,20,tr("picturebridge.button.copy_url")));if(!started){started=true;load(false);}}
    @Override protected void actionPerformed(GuiButton b){if(b.id==0)mc.displayGuiScreen(parent);else if(b.id==1)load(true);else if(b.id==2){setClipboardString(uri.toASCIIString());copied=System.nanoTime()+2_000_000_000L;}}
    @Override public void drawScreen(int mx,int my,float d){drawRect(0,0,width,height,0xC0101115);Area a=area();drawRect(a.l,a.t,a.r,a.b,0xB0101115);border(a,0xFF3A3D46);if(texture!=null)drawImage(a);else drawCenteredString(fontRendererObj,error.isEmpty()?tr("picturebridge.status.loading",dots()):error,a.cx(),a.cy()-4,error.isEmpty()?0xD9E2F2:0xFF6B6B);drawCenteredString(fontRendererObj,tr("picturebridge.screen.title"),width/2,8,0xFFFFFF);drawCenteredString(fontRendererObj,tr(System.nanoTime()<copied?"picturebridge.status.copied":"picturebridge.status.hint"),width/2,Math.max(0,height-45),0xA0A7B4);super.drawScreen(mx,my,d);}
    private void drawImage(Area a){texture.update(System.nanoTime());double s=Math.min((a.w()-4D)/texture.width(),(a.h()-4D)/texture.height())*zoom;int w=Math.max(1,(int)Math.round(texture.width()*s)),h=Math.max(1,(int)Math.round(texture.height()*s)),x=(int)Math.round(a.cx()-w/2D+panX),y=(int)Math.round(a.cy()-h/2D+panY),gs=new net.minecraft.client.gui.ScaledResolution(mc).getScaleFactor();GL11.glEnable(GL11.GL_SCISSOR_TEST);GL11.glScissor((a.l+1)*gs,(height-a.b+1)*gs,Math.max(1,a.w()-2)*gs,Math.max(1,a.h()-2)*gs);mc.getTextureManager().bindTexture(texture.location());GL11.glColor4f(1,1,1,1);drawModalRectWithCustomSizedTexture(x,y,0,0,w,h,texture.width(),texture.height());GL11.glDisable(GL11.GL_SCISSOR_TEST);String s1=texture.animated()?tr("picturebridge.status.ready_animated",texture.width(),texture.height(),texture.frames(),Math.round(zoom*100)):tr("picturebridge.status.ready",texture.width(),texture.height(),Math.round(zoom*100));fontRendererObj.drawStringWithShadow(s1,width-fontRendererObj.getStringWidth(s1)-8,8,0xB8C7D9);}
    @Override protected void mouseClicked(int x,int y,int b)throws IOException{super.mouseClicked(x,y,b);if(texture!=null&&b==0&&area().contains(x,y)){long n=System.nanoTime();if(n-lastClick<250_000_000L)reset();else dragging=true;lastClick=n;lastX=x;lastY=y;}}@Override protected void mouseClickMove(int x,int y,int b,long t){if(dragging&&texture!=null&&b==0){panX+=x-lastX;panY+=y-lastY;lastX=x;lastY=y;}}@Override protected void mouseReleased(int x,int y,int b){dragging=false;super.mouseReleased(x,y,b);}@Override public void handleMouseInput()throws IOException{super.handleMouseInput();int wheel=Mouse.getEventDWheel();if(texture!=null&&wheel!=0){zoom=Math.max(.1,Math.min(12,zoom*Math.pow(1.2,wheel>0?1:-1)));}}@Override protected void keyTyped(char c,int k)throws IOException{if(texture!=null&&k==Keyboard.KEY_R)reset();else super.keyTyped(c,k);}@Override public void onGuiClosed(){generation++;destroy();super.onGuiClosed();}@Override public boolean doesGuiPauseGame(){return false;}
    private void load(boolean refresh){final int req=++generation;error="";reset();destroy();RemoteImageLoader.INSTANCE.loadImage(uri,refresh).whenComplete((d,t)->Minecraft.getMinecraft().addScheduledTask(()->finish(req,d,t)));}private void finish(int req,DecodedImage d,Throwable t){if(req!=generation)return;if(t!=null||d==null)error=errorText(t);else texture=new AnimatedForgeTexture(mc,d);}private void destroy(){if(texture!=null)texture.close();texture=null;}private void reset(){zoom=1;panX=panY=0;}private Area area(){return new Area(8,25,Math.max(9,width-8),Math.max(26,height-51));}private static String tr(String k,Object...a){return I18n.format(k,a);}private static String dots(){int n=(int)(System.currentTimeMillis()/350%4);return n==0?"":n==1?".":n==2?"..":"...";}private static String errorText(Throwable t){Throwable c=t;while((c instanceof CompletionException||c instanceof ExecutionException)&&c.getCause()!=null)c=c.getCause();if(c instanceof ImageLoadException){ImageLoadException e=(ImageLoadException)c;return tr(e.translationKey(),e.arguments());}return tr("picturebridge.error.network",c==null||c.getMessage()==null?"unknown error":c.getMessage());}private static void border(Area a,int c){drawRect(a.l,a.t,a.r,a.t+1,c);drawRect(a.l,a.b-1,a.r,a.b,c);drawRect(a.l,a.t,a.l+1,a.b,c);drawRect(a.r-1,a.t,a.r,a.b,c);}private static final class Area{final int l,t,r,b;Area(int l,int t,int r,int b){this.l=l;this.t=t;this.r=r;this.b=b;}int w(){return r-l;}int h(){return b-t;}int cx(){return l+w()/2;}int cy(){return t+h()/2;}boolean contains(double x,double y){return x>=l&&x<r&&y>=t&&y<b;}}
}
