# Gradle
org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Shared mod metadata
mod_version=0.4.0
maven_group=haaa.picturebridge

# Build tooling
loom_version=1.17.17

# Fabric 1.21.11
minecraft_1_21_11_version=1.21.11
yarn_1_21_11_mappings=1.21.11+build.4
loader_1_21_11_version=0.19.3
