pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'PictureBridge'

include(
        'fabric-1.14',
        'fabric-1.14.1',
        'fabric-1.14.2',
        'fabric-1.14.3',
        'fabric-1.14.4',
        'fabric-1.15',
        'fabric-1.15.1',
        'fabric-1.15.2',
        'fabric-1.16',
        'fabric-1.16.1',
        'fabric-1.16.2',
        'fabric-1.16.3',
        'fabric-1.16.4',
        'fabric-1.16.5',
        'fabric-1.17',
        'fabric-1.17.1',
        'fabric-1.18',
        'fabric-1.18.1',
        'fabric-1.18.2',
        'fabric-1.19',
        'fabric-1.19.1',
        'fabric-1.19.2',
        'fabric-1.19.3',
        'fabric-1.19.4',
        'fabric-1.20.1',
        'fabric-1.20.6',
        'fabric-1.21.1',
        'fabric-1.21.4',
        'fabric-1.21.8',
        'fabric-1.21.10',
        'fabric-1.21.11',
        'fabric-26.1',
        'fabric-26.2'
)
