buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net/' }
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:${project.ext.forgeTarget.fg}"
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

def target = project.ext.forgeTarget
def rootProperties = new Properties()
new File(project.projectDir, '../../gradle.properties').withInputStream { rootProperties.load(it) }
def modVersion = rootProperties.mod_version
version = modVersion
group = 'haaa.picturebridge'
archivesBaseName = "picturebridge-forge-${target.minecraft}"
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = target.coordinate
    runDir = 'run'
    mappings = target.mappings
}

sourceSets.main.java.setSrcDirs([
        project.file("../${target.source}/src/main/java"),
        project.file('../forge-common/src/main/java')
])
sourceSets.main.resources.setSrcDirs([
        project.file("../${target.resources}/src/main/resources")
])

processResources {
    inputs.property 'version', project.version
    inputs.property 'mcversion', target.minecraft
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand version: project.version, mcversion: target.minecraft
    }
    from(sourceSets.main.resources.srcDirs) { exclude 'mcmod.info' }
}

tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }
