license="MIT"

[[mods]]
modId="picturebridge"
version="${mod_version}"
displayName="PictureBridge"
authors="hutuyee"
description='''
在 Minecraft 客户端内查看 ShitBot 转发的 QQ 图片。
'''

[[mixins]]
config="picturebridge.neoforge.mixins.json"

[[dependencies.picturebridge]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.picturebridge]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version}]"
ordering="NONE"
side="CLIENT"
