plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = mod_version
group = 'haaa.picturebridge'
base.archivesName = 'picturebridge-forge-1.16.5'

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'official', version: minecraft_version
    runs {
        client {
            workingDirectory project.file('run')
            mods {
                picturebridge { source sourceSets.main }
            }
        }
    }
}

sourceSets.main.java.srcDir '../forge-common/src/main/java'

dependencies {
    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"
}

tasks.named('processResources', ProcessResources).configure {
    def replacements = [
            version: mod_version,
            minecraft_version: minecraft_version,
            forge_version: forge_version
    ]
    inputs.properties replacements
    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replacements
    }
}

tasks.named('jar', Jar).configure {
    finalizedBy 'reobfJar'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
